In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r"E:/Data Science/1/insurance.csv")

In [3]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [5]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [7]:
df = df[["sex","smoker","region","age","bmi","children","charges"]]

In [8]:
df.head()

sex smoker     region  age     bmi  children      charges
0  female    yes  southwest   19  27.900         0  16884.92400
1    male     no  southeast   18  33.770         1   1725.55230
2    male     no  southeast   28  33.000         3   4449.46200
3    male     no  northwest   33  22.705         0  21984.47061
4    male     no  northwest   32  28.880         0   3866.85520

In [9]:
x = df.drop("charges",axis=1)
y = df["charges"]

In [10]:
x

sex smoker     region  age     bmi  children
0     female    yes  southwest   19  27.900         0
1       male     no  southeast   18  33.770         1
2       male     no  southeast   28  33.000         3
3       male     no  northwest   33  22.705         0
4       male     no  northwest   32  28.880         0
...      ...    ...        ...  ...     ...       ...
1333    male     no  northwest   50  30.970         3
1334  female     no  northeast   18  31.920         0
1335  female     no  southeast   18  36.850         0
1336  female     no  southwest   21  25.800         0
1337  female    yes  northwest   61  29.070         0

[1338 rows x 6 columns]

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
one = OneHotEncoder(sparse=False,handle_unknown='ignore')

In [13]:
x_dup =pd.DataFrame(one.fit_transform(x.iloc[:,:3]),columns=one.get_feature_names_out())
x_dup

sex_female  sex_male  smoker_no  smoker_yes  region_northeast  \
0            1.0       0.0        0.0         1.0               0.0   
1            0.0       1.0        1.0         0.0               0.0   
2            0.0       1.0        1.0         0.0               0.0   
3            0.0       1.0        1.0         0.0               0.0   
4            0.0       1.0        1.0         0.0               0.0   
...          ...       ...        ...         ...               ...   
1333         0.0       1.0        1.0         0.0               0.0   
1334         1.0       0.0        1.0         0.0               1.0   
1335         1.0       0.0        1.0         0.0               0.0   
1336         1.0       0.0        1.0         0.0               0.0   
1337         1.0       0.0        0.0         1.0               0.0   

      region_northwest  region_southeast  region_southwest  
0                  0.0               0.0               1.0  
1                  0.0               1.0               0.0  
2                  0.0               1.0               0.0  
3                  1.0               0.0               0.0  
4                  1.0               0.0               0.0  
...                ...               ...               ...  
1333               1.0               0.0               0.0  
1334               0.0               0.0               0.0  
1335               0.0               1.0               0.0  
1336               0.0               0.0               1.0  
1337               1.0               0.0               0.0  

[1338 rows x 8 columns]

In [14]:
x.drop(columns=["sex","smoker","region"],inplace=True)

In [15]:
x

age     bmi  children
0      19  27.900         0
1      18  33.770         1
2      28  33.000         3
3      33  22.705         0
4      32  28.880         0
...   ...     ...       ...
1333   50  30.970         3
1334   18  31.920         0
1335   18  36.850         0
1336   21  25.800         0
1337   61  29.070         0

[1338 rows x 3 columns]

In [16]:
x = pd.concat([x,x_dup],axis=1)
x

age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes  \
0      19  27.900         0         1.0       0.0        0.0         1.0   
1      18  33.770         1         0.0       1.0        1.0         0.0   
2      28  33.000         3         0.0       1.0        1.0         0.0   
3      33  22.705         0         0.0       1.0        1.0         0.0   
4      32  28.880         0         0.0       1.0        1.0         0.0   
...   ...     ...       ...         ...       ...        ...         ...   
1333   50  30.970         3         0.0       1.0        1.0         0.0   
1334   18  31.920         0         1.0       0.0        1.0         0.0   
1335   18  36.850         0         1.0       0.0        1.0         0.0   
1336   21  25.800         0         1.0       0.0        1.0         0.0   
1337   61  29.070         0         1.0       0.0        0.0         1.0   

      region_northeast  region_northwest  region_southeast  region_southwest  
0                  0.0               0.0               0.0               1.0  
1                  0.0               0.0               1.0               0.0  
2                  0.0               0.0               1.0               0.0  
3                  0.0               1.0               0.0               0.0  
4                  0.0               1.0               0.0               0.0  
...                ...               ...               ...               ...  
1333               0.0               1.0               0.0               0.0  
1334               1.0               0.0               0.0               0.0  
1335               0.0               0.0               1.0               0.0  
1336               0.0               0.0               0.0               1.0  
1337               0.0               1.0               0.0               0.0  

[1338 rows x 11 columns]

In [17]:
import joblib

In [18]:
joblib.dump(one,"OneHotee.joblib")

['OneHotee.joblib']

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [20]:
model = RandomForestRegressor()

In [21]:
from sklearn.model_selection import GridSearchCV

In [22]:
param_grid={
        "n_estimators":[100,500],
        "max_features":['auto','sqrt','log2'],
        "max_depth":[4,5,6,7,8],
         "criterion":['squared_error']   
}

In [23]:
grid_model = GridSearchCV(estimator=model,param_grid=param_grid,cv=5)

In [24]:
# grid_model.fit(x,y)

In [25]:
# grid_model.best_params_

In [26]:
regressor = RandomForestRegressor(n_estimators =100,max_features='auto',max_depth=8,criterion="squared_error")

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=32)

In [29]:
regressor.fit(x_train,y_train)

RandomForestRegressor(max_depth=8, max_features='auto')

In [30]:
regressor.score(x_train,y_train)

0.9545622568616117

In [31]:
regressor.score(x_test,y_test)

0.8500967230162468

In [32]:
pre = regressor.predict(x_test)

In [33]:
pre

array([17017.76272745, 16967.03344885,  5370.81488451, 13482.48102338,
       11283.3414918 ,  3142.50399594, 44510.19803875,  4548.02304081,
        6616.27172997, 10408.46426086,  3836.58323818,  3975.4130298 ,
       17880.06324199, 49969.14924018,  9901.94165339, 43337.21266737,
       12319.6057177 , 12053.00115571, 11451.36738355, 17449.79235337,
        6766.39843204, 14773.88691347, 15692.93493354,  6387.77827503,
       45197.70156697,  2647.00258537,  7556.17674689, 17046.92286874,
       10452.03432516, 20289.20726464,  2420.89219959,  7616.45746748,
        9381.22875943, 15670.72851606,  9953.13189031, 39941.62041376,
        7462.04139511,  5018.57690056, 25971.2810455 , 15108.60802603,
        9157.85667347,  1693.45266732, 12360.05579124,  2563.66477488,
        5683.68365773,  9074.3569954 ,  6726.53070261, 11308.89775567,
       15092.54869269, 35757.62578311, 16896.32185417, 45054.14601004,
        4722.00345255,  4327.59102308, 15678.04003701, 17833.0430953 ,
      

In [34]:
from sklearn.metrics import mean_squared_error,r2_score

In [35]:
mean_squared_error(y_test,pre)

20582150.551227205

In [36]:
r2_score(y_test,pre)

0.8500967230162468

In [37]:
np.sqrt(mean_squared_error(y_test,pre))

4536.755509306977

In [38]:
joblib.dump(regressor,"regressor.pkl")

['regressor.pkl']

In [39]:
check = df.copy()

In [40]:
check=check.head(1)
check

sex smoker     region  age   bmi  children    charges
0  female    yes  southwest   19  27.9         0  16884.924

In [41]:
check.drop("charges",axis=1,inplace=True)

In [42]:
check

sex smoker     region  age   bmi  children
0  female    yes  southwest   19  27.9         0

In [43]:
one_hot = joblib.load("OneHotee.joblib")
one_hot

OneHotEncoder(handle_unknown='ignore', sparse=False)

In [44]:
l=one_hot.transform(check.iloc[:,:3])
l

array([[1., 0., 0., 1., 0., 0., 0., 1.]])

In [45]:
c = one_hot.get_feature_names_out()

In [46]:
c

array(['sex_female', 'sex_male', 'smoker_no', 'smoker_yes',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest'], dtype=object)

In [47]:
t = pd.DataFrame(l,columns=c)
t

sex_female  sex_male  smoker_no  smoker_yes  region_northeast  \
0         1.0       0.0        0.0         1.0               0.0   

   region_northwest  region_southeast  region_southwest  
0               0.0               0.0               1.0

In [48]:
l2 = check.iloc[:,3:]

In [49]:
l2

age   bmi  children
0   19  27.9         0

In [50]:
final = pd.concat([l2,t],axis=1)
final

age   bmi  children  sex_female  sex_male  smoker_no  smoker_yes  \
0   19  27.9         0         1.0       0.0        0.0         1.0   

   region_northeast  region_northwest  region_southeast  region_southwest  
0               0.0               0.0               0.0               1.0

In [51]:
final_model = joblib.load("regressor.pkl")
final_model

RandomForestRegressor(max_depth=8, max_features='auto')

In [52]:
final_model.predict(final)

array([17077.24102149])